---
# tasks file for db_role

- name: Install 'mariadb-server' and 'MySQL-python' packages
  #warn: no # Disable all warnings from module 'yum' in  
  ansible.builtin.command: /usr/bin/yum install {{ item }} -y
  loop: "{{ db_packages }}"
  args:
    warn: no # Disable all warnings from module 'yum' in

- name: Ensure 'mariadb' service is started and enabled
  service:
    name: mariadb
    state: started
    enabled: true

- name: Create "{{ db_name }}" database
  mysql_db:
    name: "{{ db_name }}"
    state: present

- name: >
    Create database user "{{ db_user }}" with "{{ db_password }}"
    and grant him "{{ db_name }}" '*.*:ALL privileges'
  no_log: true # To keep sensitive values out of my logs!
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: '*.*:ALL'
    state: present

...