---
- name: CREATE USERS WITH AN ENCRYPTED CREDENTIALS
  hosts: centos_nodes
  vars:
    # User's comment/description. Appears in /etc/passwd: 
    comment: "Ansible-generated user!"
  vars_files:
    - secrets.yaml

  tasks:
    - name: Create these super secret users
      user:
        name: "{{ user.username }}"
        # We must set a password hash to wipe out a potentional warning:
        password: "{{ user.password | password_hash('sha512') }}"
        comment: "{{ comment }}"
        state: present
      loop: "{{ credentials }}"
      loop_control:
        # Define a custom loop variable naming (item -> user):
        loop_var: user
        # Set pause for 5 seconds:
        pause: 5

...
