---
- name: install MariaDB
  hosts: centos_nodes
  vars_files:
    - vars/main.yaml
  vars:
    # Required packages:
    db_packages: 
      - mariadb-server
      - python3-PyMySQL 
  
  tasks:
    - name: Install 'mariadb-server' and 'MySQL-python' packages
      warn: false # Disable all warnings from module 'yum' in  
      ansible.builtin.command: /usr/bin/yum install {{ item }} -y
      loop: "{{ db_packages }}"

    - name: Ensure 'mariadb' service is started and enabled
      service:
        name: mariadb
        state: started
        enabled: true

    - name: Create "{{ db_name }}" database
      mysql_db:
        name: "{{ db_name }}"
        state: present

    - name: >
        Create database user "{{ db_user }}" with "{{ db_password }}"
        and grant him "{{ db_name }}" '*.*:ALL privileges'
      no_log: true # To keep sensitive values out of my logs!
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: '*.*:ALL'
        state: present

...
