---
# handlers file for nginx_role

- name: restart_nginx_service
  service:
    name: nginx
    state: restarted

- name: reload_firewalld_service
  service:
    name: firewalld
    state: reloaded

...